name: Build Mod

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Build Mod
        run: ./gradlew build

      - name: List Build Files (debug)
        run: ls -R build

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
